"use strict";

const assert=require("node:assert/strict");
const base=process.env.MILTON_BASE_URL||"http://127.0.0.1:4173";
async function call(token,path,{method="GET",body}={}){const response=await fetch(base+path,{method,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});const type=response.headers.get("content-type")||"",value=type.includes("json")?await response.json():await response.text();if(!response.ok){const error=new Error(value.error||String(value));error.status=response.status;error.value=value;throw error}return value}
async function expectStatus(status,fn){try{await fn();assert.fail(`Expected HTTP ${status}`)}catch(error){assert.equal(error.status,status)}}
async function login(login,password="demo123"){return (await call("","/api/login",{method:"POST",body:{login,password}})).token}

(async()=>{
  const stamp=String(Date.now()).slice(-7),admin=await login("admin@milton.kz"),bootstrap=await call(admin,"/api/bootstrap"),managerRole=bootstrap.roles.find(r=>r.systemKey==="MANAGER"),closerRole=bootstrap.roles.find(r=>r.systemKey==="CLOSER");
  const managerLogin=`qa.manager.${stamp}@milton.kz`,closerLogin=`qa.closer.${stamp}@milton.kz`,password="qaPass123";
  const manager=await call(admin,"/api/admin/users",{method:"POST",body:{name:`QA Manager ${stamp}`,login:managerLogin,password,roleId:managerRole.id,profileStatus:"WORKING"}}),closer=await call(admin,"/api/admin/users",{method:"POST",body:{name:`QA Closer ${stamp}`,login:closerLogin,password,roleId:closerRole.id,profileStatus:"WORKING"}});
  const managerToken=await login(managerLogin,password),closerToken=await login(closerLogin,password);
  const managerBoot=await call(managerToken,"/api/bootstrap"),closerBoot=await call(closerToken,"/api/bootstrap");assert.equal(managerBoot.me.role,"MANAGER");assert.equal(closerBoot.me.role,"CLOSER");assert.equal(managerBoot.access.permissions["analytics.view"],true);assert.equal(closerBoot.access.permissions["analytics.view"],true);assert.deepEqual(managerBoot.analyticsDimensions.users.map(u=>u.id),[manager.id]);assert.deepEqual(closerBoot.analyticsDimensions.users.map(u=>u.id),[closer.id]);
  await expectStatus(403,()=>call(managerToken,"/api/admin/config/tags",{method:"POST",body:{name:"Denied"}}));await expectStatus(403,()=>call(closerToken,"/api/clients",{method:"POST",body:{}}));await expectStatus(404,()=>call(managerToken,"/api/clients/cl_3"));

  const date="2026-09-01";await call(closerToken,"/api/slots/generate",{method:"POST",body:{closerId:closer.id,date,start:"10:00",end:"13:00",interval:60}});let slots=await call(managerToken,`/api/slots?closerId=${closer.id}&date=${date}`);assert.equal(slots.filter(s=>s.status==="FREE").length,3);
  const client1=await call(managerToken,"/api/clients",{method:"POST",body:{name:`QA Payment ${stamp}`,phone:`+7700${stamp}`,closerId:closer.id,slotId:slots[0].id,leadSourceId:"src_1",tagIds:["tag_1"],comment:"E2E registration comment"}});
  const avatarData="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=";await call(managerToken,"/api/profile",{method:"PUT",body:{avatarUrl:avatarData}});await call(closerToken,"/api/profile",{method:"PUT",body:{avatarUrl:avatarData}});assert.match((await call(await login(managerLogin,password),"/api/bootstrap")).me.avatarUrl,/^\/api\/users\//);assert.match((await call(await login(closerLogin,password),"/api/bootstrap")).me.avatarUrl,/^\/api\/users\//);
  await call(closerToken,`/api/clients/${client1.id}/notes`,{method:"POST",body:{text:"E2E closer note"}});await call(closerToken,`/api/clients/${client1.id}/status`,{method:"POST",body:{statusId:"st_payment",amount:55000,paymentMethodId:"method_1",paymentDate:date,paymentComment:"E2E payment"}});
  const managerView=await call(managerToken,`/api/clients/${client1.id}`);assert.equal(managerView.payments.filter(p=>!p.voidedAt).length,1);assert.equal(managerView.notes.length,1);assert.ok(managerView.history.some(h=>h.eventType==="PAYMENT_CREATED"));
  let analytics=await call(admin,`/api/analytics?from=${date}&to=${date}&managerId=${manager.id}&closerId=${closer.id}&dateType=trial`);assert.equal(analytics.kpis.trials,1);assert.equal(analytics.kpis.payments,1);assert.equal(analytics.kpis.convertedClients,1);assert.equal(analytics.kpis.revenue,55000);

  slots=await call(managerToken,`/api/slots?closerId=${closer.id}&date=${date}`);const client2=await call(managerToken,"/api/clients",{method:"POST",body:{name:`QA Refusal ${stamp}`,phone:`+7710${stamp}`,closerId:closer.id,slotId:slots.find(s=>s.status==="FREE").id,leadSourceId:"src_2",tagIds:["tag_2"],comment:"Second E2E client"}});
  await expectStatus(403,()=>call(managerToken,`/api/clients/${client2.id}/status`,{method:"POST",body:{statusId:"st_payment",amount:1,paymentMethodId:"method_1",paymentDate:date}}));await expectStatus(403,()=>call(managerToken,`/api/clients/${client2.id}/status`,{method:"POST",body:{statusId:"st_refusal",refusalReasonId:"reason_1"}}));
  const nextDate="2026-09-02";await call(closerToken,"/api/slots/generate",{method:"POST",body:{closerId:closer.id,date:nextDate,start:"10:00",end:"12:00",interval:60}});const nextSlots=await call(closerToken,`/api/slots?closerId=${closer.id}&date=${nextDate}`);await call(managerToken,`/api/clients/${client2.id}/status`,{method:"POST",body:{statusId:"st_reschedule",newSlotId:nextSlots[0].id}});await call(closerToken,`/api/clients/${client2.id}/status`,{method:"POST",body:{statusId:"st_refusal",refusalReasonId:"reason_1"}});
  await call(closerToken,"/api/slots/generate",{method:"POST",body:{closerId:closer.id,date,start:"13:00",end:"14:00",interval:60}});slots=await call(managerToken,`/api/slots?closerId=${closer.id}&date=${date}`);const client3=await call(managerToken,"/api/clients",{method:"POST",body:{name:`QA No-show ${stamp}`,phone:`+7720${stamp}`,closerId:closer.id,slotId:slots.find(s=>s.status==="FREE").id,leadSourceId:"src_1",tagIds:[],comment:"Manager no-show test"}});await call(managerToken,`/api/clients/${client3.id}/status`,{method:"POST",body:{statusId:"st_no_show"}});assert.equal((await call(managerToken,`/api/clients/${client3.id}`)).client.currentStatusId,"st_no_show");
  const client4=await call(managerToken,"/api/clients",{method:"POST",body:{name:`QA Closer Reschedule ${stamp}`,phone:`+7730${stamp}`,closerId:closer.id,slotId:nextSlots[1].id,leadSourceId:"src_1",tagIds:[],comment:"Closer reschedule test"}}),thirdDate="2026-09-03";await call(closerToken,"/api/slots/generate",{method:"POST",body:{closerId:closer.id,date:thirdDate,start:"10:00",end:"11:00",interval:60}});const thirdSlots=await call(closerToken,`/api/slots?closerId=${closer.id}&date=${thirdDate}`);await call(closerToken,`/api/clients/${client4.id}/status`,{method:"POST",body:{statusId:"st_reschedule",newSlotId:thirdSlots[0].id}});await call(closerToken,`/api/clients/${client4.id}/status`,{method:"POST",body:{statusId:"st_no_show"}});assert.equal((await call(closerToken,`/api/clients/${client4.id}`)).client.currentStatusId,"st_no_show");
  const refused=await call(admin,`/api/clients/${client2.id}`);assert.equal(refused.trials.length,2);assert.ok(refused.history.some(h=>h.eventType==="TRIAL_RESCHEDULED"));assert.equal(refused.client.currentStatusId,"st_refusal");analytics=await call(admin,`/api/analytics?from=2026-08-31&to=${nextDate}&refusalReasonId=reason_1`);assert.ok(analytics.refusals.some(row=>row.id==="reason_1"&&row.count>=1));

  const activePayment=managerView.payments.find(p=>!p.voidedAt);await call(admin,`/api/payments/${activePayment.id}/correct`,{method:"POST",body:{amount:57000,paymentMethodId:"method_1",paymentDate:date,comment:"Corrected E2E payment"}});const corrected=await call(admin,`/api/clients/${client1.id}`);assert.equal(corrected.payments.filter(p=>!p.voidedAt)[0].amount,57000);assert.ok(corrected.history.some(h=>h.eventType==="PAYMENT_CORRECTED"));

  const tempTag=await call(admin,"/api/admin/config/tags",{method:"POST",body:{name:`QA Tag ${stamp}`,color:"#123456",sortOrder:99}});await call(admin,`/api/admin/config/tags/${tempTag.id}/archive`,{method:"POST"});await call(admin,`/api/admin/config/tags/${tempTag.id}/restore`,{method:"POST"});
  const trialsCsv=await call(admin,`/api/export/trials.csv?from=${date}&to=${nextDate}&managerId=${manager.id}`),paymentsCsv=await call(admin,`/api/export/payments.csv?from=${date}&to=${nextDate}&managerId=${manager.id}`);assert.match(trialsCsv,/QA Payment/);assert.match(paymentsCsv,/57000/);
  await call(admin,`/api/admin/users/${closer.id}/archive`,{method:"POST"});await expectStatus(401,()=>login(closerLogin,password));const persisted=await call(admin,`/api/clients/${client1.id}`);assert.equal(persisted.client.closer.id,closer.id);assert.equal(persisted.payments.filter(p=>!p.voidedAt)[0].amount,57000);
  console.log(JSON.stringify({ok:true,managerLogin,closerLogin,password,managerId:manager.id,closerId:closer.id,client1:client1.id,client2:client2.id,client3:client3.id,client4:client4.id,revenue:57000,note:"Profile photos persisted; closer archived intentionally in scenario 2"},null,2));
})().catch(error=>{console.error(error.stack||error);process.exitCode=1});
